//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadNatura
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinica
    {
        public int id { get; set; }
        public int idPaciente { get; set; }
        public int idDermatologo { get; set; }
        public string antecedentes { get; set; }
        public string sintomas { get; set; }
        public string diagnosticos { get; set; }
        public string tratamientos { get; set; }
        public string observaciones { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual Dermatologo Dermatologo { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
