//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadNatura
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NaturaEntities : DbContext
    {
        public NaturaEntities()
            : base("name=NaturaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Dermatologos> Dermatologos { get; set; }
        public virtual DbSet<HistoriasClinicas> HistoriasClinicas { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<Pagos> Pagos { get; set; }
        public virtual DbSet<Reconsultas> Reconsultas { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    
        public virtual ObjectResult<paCitasListar_Result> paCitasListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paCitasListar_Result>("paCitasListar", parametroParameter);
        }
    
        public virtual ObjectResult<paDermatologosListar_Result> paDermatologosListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paDermatologosListar_Result>("paDermatologosListar", parametroParameter);
        }
    
        public virtual ObjectResult<paHistoriasClinicasListar_Result> paHistoriasClinicasListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paHistoriasClinicasListar_Result>("paHistoriasClinicasListar", parametroParameter);
        }
    
        public virtual ObjectResult<paPacientesListar_Result> paPacientesListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPacientesListar_Result>("paPacientesListar", parametroParameter);
        }
    
        public virtual ObjectResult<paPagosListar_Result> paPagosListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paPagosListar_Result>("paPagosListar", parametroParameter);
        }
    
        public virtual ObjectResult<paReconsultasListar_Result> paReconsultasListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paReconsultasListar_Result>("paReconsultasListar", parametroParameter);
        }
    
        public virtual ObjectResult<paUsuariosListar_Result> paUsuariosListar(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<paUsuariosListar_Result>("paUsuariosListar", parametroParameter);
        }
    }
}
